### PR TITLE
feat: add hostio-caching feature

### PR DESCRIPTION
**Pull request by qalisander**
## Description

Provides the default feature `hostio-caching` to `stylus-sdk`.
When disabled, any function that uses caching behavior to query a host node will stop doing so.

e.g. `msg::sender()` would query actual sender from host node each time (not just once), when `hostio-caching` feature disabled.

Extremely convenient for unit test mocks.

## Checklist

- [x] I have documented these changes where necessary.
- [x] I have read the [DCO][DCO] and ensured that these changes comply.
- [x] I assign this work under its [open source licensing][terms].

[DCO]: https://github.com/OffchainLabs/stylus-sdk-rs/blob/stylus/licenses/DCO.txt
[terms]: https://github.com/OffchainLabs/stylus-sdk-rs/blob/stylus/licenses/COPYRIGHT.md

### CODE REVIEW

**Review by rauljordan — APPROVED** [review]
lgtm, thanks for putting this together

**Comment by qalisander** [comment]
@rauljordan  I see that `Smoke Test` workflows cannot pass due to this error: `error: a value is required for '--private-key <PRIVATE_KEY>' but none was supplied`.
Probably configuration issue, not sure what is wrong..

**Comment by rauljordan** [comment]
hi @qalisander looks like it is a repository secret that is inaccessible to external contributor PRs. We'll fix it by instead using the Arbitrum Nitro testnode in CI which creates a devnet instead of deploying to a public testnet each time we run a PR. That should improve our smoke test experience and will allow your PR to pass. I'll work on this today

**Comment by rauljordan** [comment]
Develop is now ready with the ci fix @qalisander , this pr should pass after you sync the branch

**Comment by qalisander** [comment]
Done

**Pull request merged**
